### ISSUE TITLE
[FEATURE] allow fractional trades in crypto

### ISSUE THREAD

**Issue by jpdeleon** [enzoampil/fastquant#222]
Currently, `backtest` only allows buying and selling integer units of stocks.
So the code below will not show any trade: 
```python
from fastquant import backtest, get_crypto_data

crypto = get_crypto_data("BTC/USDT", 
                         "2018-12-01", 
                         "2019-12-31"
                        )
results = backtest('smac', 
                   crypto, 
                   fast_period=[7,14,21,28], 
                   slow_period=[30,45,60,75],
                   plot=False,
                   verbose=False,
                   init_cash=100
                  )
```
In bitcoin transactions however, fractional units are common. 
So we should introduce a parameter in `backtest` that allows this.

**Comment by jpdeleon** [comment]
@enzoampil any thoughts on this? Is this a high priority?

**Comment by enzoampil** [comment]
@jpdeleon Good point on this. My current thought is not so much since I think people typically focus on % return, and so won't mind just using the default init_cash. Although, I do see this as a potential issue since the price of one bitcoin is so large, so even with 100K default, a lot of cash could be left unutilized in the backtest.

I agree that this should be high priority since it's likely a core feature for crypto users.

**Comment by enzoampil** [comment]
Bumping this up since it's especially important now that BTC / USDT is at 57K ...

**Comment by enzoampil** [comment]
@jpdeleon fractional trading is already supported after this PR #377 :smile:
