### ISSUE TITLE
[BUG] Sentiment strategy backtest results in AttributeError

### ISSUE THREAD

**Issue by deepettas** [enzoampil/fastquant#246]
#### Problem description

Following the example on the readme about using sentiment to backtest, I sumbled upon this error: 
`AttributeError: 'BarContainer' object has no attribute 'get_zorder'
`
It seems to be a backtrader error.
 I made sure to use the versions proposed in the requirements.txt file
#### Example

```python
from fastquant import get_yahoo_data, get_bt_news_sentiment
data = get_yahoo_data("TSLA", "2020-01-01", "2020-07-04")
sentiments = get_bt_news_sentiment(keyword="tesla", page_nums=3)
backtest("sentiment", data, sentiments=sentiments, senti=0.2)

```

#### Expected behavior
Same as the other backtests

#### Environment

-  platform OSX
-  fastquant version 0.1.3.23
-  installation method  pip

**Comment by rafmacalaba** [comment]
Hi @deepettas thanks for raising this bug issue, this is occuring because of the inconsistencies of the dates in the data and the sentiments.

I'm going to add to the backtest documentation to have the current date and timedelta for the start  and end dates for this to not confuse other users that are using fastquant.

Thanks for using fastquant and I hope you'll find it useful :D
