### ISSUE TITLE
[FEATURE] Document recommended installation method

### ISSUE THREAD

**Issue by jgendrinal** [enzoampil/fastquant#265]
Install python packages through the python interpreter by default

![image](https://user-images.githubusercontent.com/24620623/95975671-08ebba80-0e49-11eb-82ac-0fcc1bd0515c.png)

**Comment by rafmacalaba** [comment]
just add python to PATH? this is babysitting

**Comment by jgendrinal** [comment]
I get this, but I'm seeing this as the default recommended in a lot of packages now, and even in pip warnings when installing.

**Comment by jpdeleon** [comment]
The most fail-proof way to install the most updated fastquant version is
```shell
python -m pip install git+https://github.com/enzoampil/fastquant.git@master
```
if via terminal, or
```shell
import sys
!{sys.executable} -m pip install git+https://github.com/enzoampil/fastquant.git@master
```
if inside jupyter notebook.

`python -m pip ...` will only differ from `pip ...` installation when pip/jupyter is somehow not in the same location as the python kernel (happens when multiple environments are present).

So I am ok with recommending `python -m pip ...` only that `pip ...` looks more elegant.
