### ISSUE TITLE
[FEATURE] Is it possible to return a dataframe result in backtest?

### ISSUE THREAD

**Issue by dmnt3d** [enzoampil/fastquant#274]
**Is your feature request related to a problem? Please describe.**
I'm trying to use Grafana visualization instead of in-built python for graphs. This will allow an interactive way of showing the data.

**Describe the solution you'd like**
Return dataframe results from backtest.

**Additional context**
Sorry. Pretty new with stocks and all. I've managed to plot historical close price data to Grafana. I want to put the SMAC now.

This project is awesome.
Thank you

**Comment by enzoampil** [comment]
Hi @dmnt3d , thank you for using fastquant! Currently, we have a `return_history` parameter than you can set to `True` when you run you backtest, which will return a `dict` which contains some of the historical logs from the backtest, where each type of log is stored as a dataframe object.

In order to get the historical SMAC (in which case I assume you want the fast moving average, and slow moving average lines), we will have to adjust the code to include the historical indicators in the "periodic" history dataframe.

We can add this to the backlog as a feature request :smile:

**Comment by dmnt3d** [comment]
salamat sir @enzoampil 

One last thing - I notice recent results for PSE only showed close prices (starting August this year from what I check). I'm missing high/low/open.

Is this expected?

**Comment by enzoampil** [comment]
@dmnt3d yes, this is correct. We've recently fully switched to using the [phisix](https://github.com/phisix-org/phisix) API which only collects closing prices for PH stocks.

**Comment by dmnt3d** [comment]
@enzoampil is there a way to switchback to the legacy way where we get the closing/low/high? What was the problem of the previous way of doing it?

**Comment by enzoampil** [comment]
@dmnt3d You can can access the indicator history now using the latest PR :smile:

https://github.com/enzoampil/fastquant/pull/276

**Comment by enzoampil** [comment]
@dmnt3d We decided to utilize an existing official API. If you want to use the old function which relies on scraping, feel free to  use the old function [here](https://github.com/enzoampil/fastquant/blob/1de45700e02b6ca86704301c28c5b306018bf27c/python/fastquant/data/stocks/pse.py#L115).
