### ISSUE TITLE
[FEATURE] Support Average True Range (ATR) from Backtrader

### ISSUE THREAD

**Issue by sgoley** [enzoampil/fastquant#275]
Backtrader has an implemented indicator for the Average True Range:
https://www.backtrader.com/docu/indautoref/#averagetruerange

I'd like that indicator to be accessible within fastquant for either solo or multi-strategy backtests. 

I could be wrong but it looks as simple to me as adding a mapping to the indicator in the backtrader library here:
https://github.com/enzoampil/fastquant/blob/master/python/fastquant/indicators/backtrader_indicators.py

However, to then make it available to the `backtest` function mapping, a new strategy would have to be created here?
https://github.com/enzoampil/fastquant/tree/master/python/fastquant/strategies

Thanks.

**Comment by enzoampil** [comment]
@sgoley Hi Scott, you are exactly correct. You can easily utiliize ATR from backtrader by adding a new strategy in the [strategies](https://github.com/enzoampil/fastquant/tree/master/python/fastquant/strategies) module and adding it to the `backtest` function mapping :smile:

Can you let me know the specific use case you have for ATR? If it's to use it as basis for stop losses, we might want to integrate it directly to the [BaseStrategy](https://github.com/enzoampil/fastquant/blob/master/python/fastquant/strategies/base.py), since this is likely useful as a feature to any trading strategy.
