### ISSUE TITLE
[FEATURE] Dividends

### ISSUE THREAD

**Issue by ChooseYourPlan** [enzoampil/fastquant#336]
I am not quite sure what happens to the dividends that one would get while holding the share in backtesting.

Maybe there should be an option for reinvesting or adding it to the account balance.

If this feature is already present, I am sorry.

**Comment by rafmacalaba** [comment]
This sounds interesting! @enzoampil do you think we can incorporate this one in fastquant? or do you have an idea if this is possible? any implementation hints will be highly appreciated. FYI @jbdelmundo @jgendrinal  @jpdeleon

**Comment by ajdajd** [comment]
I remember seeing dividends data on kissch*** before... not sure if it's something we can scrap/part of the API.

**Comment by ChooseYourPlan** [comment]
Not sure if i am right here but...

Yahoo Finance Docs says something like this.

To get the dividends expected from holding a stock we can go back to the get_quote_table() function and do:
`quote_table = si.get_quote_table("aapl")
quote_table["Forward Dividend & Yield"]
'3.28 (1.02%)'`

**Comment by enzoampil** [comment]
@rafmacalaba this is definitely doable! Though yes it will assume that the data you have also has a dividend time series.

Since we use the special CustomIndicator, we can add support for a "dividend" column in the input dataframe, and then add it to the cash balance of the portfolio so that it will be used to buy the stock (if enough to buy at least one).

Let me know if you want more specific guidance and happy to give pointers 😃

**Comment by ChooseYourPlan** [comment]
Also it would be nice to have a bool parameter where one can specify if the dividends should be reinvested

**Comment by enzoampil** [comment]
@ChooseYourPlan sounds good. Yes, Yahoo finance can be a source for the dividends. How we'll likely implement this initially is the user can add a dividend column themselves if they know how, but the `backtest` function will automatically read the `dividend` column if it exists. :smile:

**Comment by ChooseYourPlan** [comment]
Hmm I need this Feature for my Thesis about Dividend investing Strategies. Any suggestion what I should use now or how to implement it myself? Thanks in advance

**Comment by rafmacalaba** [comment]
@jbdelmundo any thoughts for implementing on `CustomIndicator`? not sure if the `sentiment-like` approach is more friendly/doable.

**Comment by rafmacalaba** [comment]
much like integrating a pandas dataframe (timestamp, dividend) with `self.data`.

**Comment by enzoampil** [comment]
@rafmacalaba  Yeah so just add a `dividend` column, then access the dividend column at the `BaseStrategy` level (yes, via `self.data` I believe). 

Because of `CustomIndicator` any of the columns in the input dataframe should be accessible at the strategy level. This is exactly what. we do for `TernaryStrategy` - it just accesses the `custom` column straight without the need for extra effort.

The difference here is the `dividend` support is ideally a `global parameter`, and so should be implemented in `BaseStrategy` :smile:

**Comment by enzoampil** [comment]
@ChooseYourPlan Hey sorry for the delay, but the dividend feature has been merged! This means that if the input dataframe has a "dividend" column, the dividends are assumed to be reinvested by default for more stock purchases (if enough to buy stocks).

To turn this off, you can explicitly set `invest_div=False` in `backtest`.

`get_stock_data` now also includes dividends when it gets data for US stocks from yahoo finance.

**Comment by ChooseYourPlan** [comment]
Wow! Amazing work guys, I will definitely check it out!
