### ISSUE TITLE
Misleading forecasting principles

### ISSUE THREAD

**Issue by thistleknot** [enzoampil/fastquant#350]
#### Problem description
Misleading forecast principles

your forecast calendar includes the dates trained on.  Took me a while to figure it out, but this should be the code.  And surprisingly it works very well!

```
from fastquant import get_crypto_data, backtest
from fbprophet import Prophet
from matplotlib import pyplot as plt

# Pull crypto data
df = get_crypto_data("BTC/USDT", "2019-01-01", "2020-05-31")

# Fit model on closing prices
ts = df.reset_index()[["dt", "close"]]
ts.columns = ['ds', 'y']
m = Prophet(daily_seasonality=True, yearly_seasonality=True).fit(ts[0:200])
#forecast = m.make_future_dataframe(periods=0, freq='D')
forecast = pd.DataFrame(df.index)
forecast.columns = ['ds']
forecast = forecast[200:]

# Predict and plot
pred = m.predict(forecast)
fig1 = m.plot(pred)
plt.title('BTC/USDT: Forecasted Daily Closing Price', fontsize=25)

# Convert predictions to expected 1 day returns
expected_1day_return = pred.set_index("ds").yhat.pct_change().shift(-1).multiply(100)

# Backtest the predictions, given that we buy bitcoin when the predicted next day return is > +1.5%, and sell when it's < -1.5%.
df["custom"] = expected_1day_return.multiply(-1)
backtest("custom", df.dropna(),upper_limit=1.5, lower_limit=-1.5)

```

**Comment by enzoampil** [comment]
Thanks for this @thistleknot , will look into this over the weekend!

**Comment by 0cv** [comment]
@thistleknot thank you, very helpful!

**Comment by enzoampil** [comment]
Thanks @thistleknot , agree that this is the more proper approach since the predictions are made "out of sample". The example in the readme was meant as a simply coded, albeit flawed approach to backtesting forecast results, which is why I mentioned `based on in-sample time series forecasts`.

Feel free to update the README with this correct out of sample prediction approach (including the output image)!

Otherwise, we'll work on updating it soon :smile:
