### ISSUE TITLE
[BUG] Issue with imports

### ISSUE THREAD

**Issue by DidierRLopes** [enzoampil/fastquant#409]
Hey, I come from [Gamestonk Terminal](https://github.com/GamestonkTerminal/GamestonkTerminal). One of our users asked about being able to integrate your library.

#### Problem description
The issue seems to be at the import level.

#### Example
<img width="1313" alt="Screenshot 2022-01-23 at 11 36 51" src="https://user-images.githubusercontent.com/25267873/150676495-e15de520-61d5-4e74-a1a7-15286c5116dd.png">
<img width="1310" alt="Screenshot 2022-01-23 at 11 37 27" src="https://user-images.githubusercontent.com/25267873/150676516-6f9986f1-ac94-44a5-9b13-e173f7d8eebc.png">

#### Expected behavior
<img width="870" alt="Screenshot 2022-01-23 at 11 38 04" src="https://user-images.githubusercontent.com/25267873/150676556-0d09d387-1ad3-449f-995d-996abf8efb99.png">

#### Environment
-  platform: OSX
-  fastquant version: 0.1.7.1
-  installation method: pip

**Comment by enzoampil** [comment]
@mikeejazmines have you seen this issue before?

**Comment by mikeejazmines** [comment]
Hi @DidierRLopes This is a backtrader and matplotlib issue. You can refer to this https://github.com/enzoampil/fastquant/pull/397

Another user has found a solution by changing their backtrader version but since we do not go this route, I find success in changing the matplotlib to 3.2.2 https://github.com/enzoampil/fastquant/issues/369

**Comment by DidierRLopes** [comment]
That does it! Thank you @mikeejazmines and @enzoampil !
