### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by geofffoster** [enzoampil/fastquant#411]
#### Problem description
using  ternary module. Setting up it to short. The first short works as expected, but the subsequent ones don't. I've made up a simple example to validate. I've changed value of initial cash and get the same result

#### Example

from fastquant import get_crypto_data, backtest, get_yahoo_data
import pandas as pd
import numpy as np

data = {'Date': ['2019-01-21', '2019-01-22', '2019-01-23', '2019-01-24','2019-01-25','2019-01-28','2019-01-29','2019-01-30','2019-01-31'], 
        'close': [100, 100, 95, 90,100,95,90,90,90],
        'custom': [0, 0, -1, 1,0,-1,0,1,0]}  
data=pd.DataFrame(data)
data.index = pd.to_datetime(data['Date'])
data=data.drop('Date',axis=1)
print(data)

signal=data.copy()
results, history = backtest("ternary",signal.dropna(), commission=0.00, plot=False,  figsize=(10, 5),init_cash=100, 
           verbose=False, fractional=False, return_history=True, allow_short=True, short_max=1)

orders=history['orders']
periodic=history['periodic']
indicators=history['indicators']
print(results[['init_cash', 'sharperatio','pnl','final_value']].T)
print(orders.set_index('dt'))
```
                 0
init_cash      100
sharperatio   None
pnl           10.0
final_value  110.0
            strat_id strat_name  type  price  size  value  commission  pnl
dt                                                                        
2019-01-24         0             sell   95.0    -1  -95.0         0.0  0.0
2019-01-25         0              buy   90.0     2   -5.0         0.0  5.0
2019-01-29         0             sell   95.0    -1   90.0         0.0  5.0
2019-01-31         0              buy   90.0     1   90.0         0.0  0.0

#### Expected behavior
I'd expect the second short pnl to be on the 'buy, instead it seems to appear in the 'sell' and my guess its doing the difference between the last one
#### Environment - laptop

-  platform (e.g. Linux, OSX, Windows):
-  fastquant version      0.1.7.1
-  installation method pip

**Comment by mikeejazmines** [comment]
Hi @geofffoster thank you for adding sample code. It made it much easier!

This is actually expected behavior. The PNL shows the pnl of the order prior because it closes in that order. The second short pnl cant be on buy as that order hasnt closed yet when that order has been made. So the pnl is shown in the order that closes the previous one.

In the example below, I changed the value to 93 just for a change of pnl value
<img width="491" alt="Screen Shot 2022-01-31 at 10 09 26 AM" src="https://user-images.githubusercontent.com/12680278/151729818-d854b3aa-c154-43df-9f5b-94cfc6a6defb.png">


Hence why pnl of 3 is shown in the buy because thats the pnl of closing the sell. Similar to a no short application, the buy would show a pnl of 0 and the sell would show the pnl of closing that buy.

**Comment by geofffoster** [comment]
thanks for the clarifcation
