### ISSUE TITLE
[BUG] use of argwhere with Panda series

### ISSUE THREAD

**Issue by jester22** [enzoampil/fastquant#85]
argwhere does not work with pandas Series
#### Problem description

Known issue with numpy [Issue Link](https://github.com/numpy/numpy/issues/15555)

Usage at:
fastquant/disclosures.py
line 435, in load_disclosures
```python
idxs1 = np.argwhere(older).flatten()
```
#### Example

```python
from fastquant import DisclosuresPSE
dpse = DisclosuresPSE(symbol=symbol, start_date=start_date, end_date=end_date, disclosure_type=disclosure_type)

Retsult: ValueError: Length of passed values is 1, index implies 12.
```

#### Solution
use instead [flatnonzero](https://docs.scipy.org/doc/numpy/reference/generated/numpy.flatnonzero.html)
```python
idxs1 = np.flatnonzero(older)
```

#### Environment
Python 3.6.9
numpy 1.18.0
pandas 1.0.3

**Comment by enzoampil** [comment]
@jester22 Can you share the argument values you used for this line?

```
dpse = DisclosuresPSE(symbol=symbol, start_date=start_date, end_date=end_date, disclosure_type=disclosure_type)
```

**Comment by enzoampil** [comment]
Seem to be getting a separate issue that stop me from replicating this error in issue #87. Will figure this out first.

**Comment by jpdeleon** [comment]
@jester22 if you create a venv, you should have numpy==1.18.0 as defined in requirements.txt. This error is for numpy==1.18.1 according to your issue link. 

I cannot reproduce this issue. 
```
older = pd.Series([True, True, False, False])
idxs1 = np.argwhere(older).flatten()
```
yields `array([0, 1])`. Issue here is due to the boolean `older`.

I plan to merge your PR because using `np.flatnonzero(df)` is identical to `np.argwhere(df).flatten()` anyway.
